trigger:
- main

resources:
- repo: self

variables:
  imageRepo: devopsapichallenge
  tag: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build image
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: Docker@2
      inputs:
       containerRegistry: 'demoazureregistrytest'
       repository: '$(imageRepo)'
       command: 'buildAndPush'
       Dockerfile: '$(Build.SourcesDirectory)/app/Dockerfile'
       tags: |
        $(tag)
        latest
    - task: PublishPipelineArtifact@1
      inputs:
        targetPath: '$(Pipeline.Workspace)/s/k8s'
        artifact: 'manifest'
        publishLocation: 'pipeline'
- stage: Deploy
  displayName: Deploy to Dev
  dependsOn: Build
  variables:
    acrsecret: k8sexampleacrauth
  jobs:
    - deployment: Deploy
      displayName: Deploy to AKS
      environment: 'AKS_ENV.default'
      pool:
       vmImage: ubuntu-latest
      strategy:
       runOnce:
         deploy:
            steps:
            - task: DownloadPipelineArtifact@2
              inputs:
                buildType: 'current'
                artifactName: 'manifest'
                targetPath: '$(Pipeline.Workspace)/manifest'
            - task: KubernetesManifest@0
              inputs:
                action: 'createSecret'
                namespace: 'default'
                secretType: 'dockerRegistry'
                secretName: '$(acrsecret)'
                dockerRegistryEndpoint: 'demoazureregistrytest'
            - task: KubernetesManifest@0
              inputs:
                action: 'deploy'
                namespace: 'default'
                manifests: |
                  $(Pipeline.Workspace)/manifest/deployment.yml
                  $(Pipeline.Workspace)/manifest/service.yml