trigger:
- main

resources:
- repo: self

variables:
  imageRepo: devopsapichallenge
  tag: '$(Build.BuildId)'

stages:
- stage: Test
  displayName: Test Application
  jobs:
  - job: Test
    displayName: Test
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: NodeTool@0
      inputs:
        versionSpec: '12.x'
      displayName: 'Install Node.js'
    - script: |
        cd app
        npm install
        npm run test
      displayName: 'npm install and test'
    - task: PublishTestResults@2
      enabled: false
      displayName: Publish Test Results
      inputs:
        testResultsFormat: 'JUnit'
        testResultsFiles: '**/test_results/jest-junit.xml'
        mergeTestResults: true  
- stage: Build
  displayName: Build image
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: Docker@2
      inputs:
       containerRegistry: 'demoazureregistrytest'
       repository: '$(imageRepo)'
       command: 'buildAndPush'
       Dockerfile: '$(Build.SourcesDirectory)/app/Dockerfile'
       tags: |
        $(tag)
    - task: PublishPipelineArtifact@1
      inputs:
        targetPath: '$(Pipeline.Workspace)/s/k8s'
        artifact: 'manifest'
        publishLocation: 'pipeline'
- stage: Deploy
  displayName: Deploy to Dev
  dependsOn: Build
  variables:
    acrsecretname: k8sexampleacrauth
  jobs:
    - deployment: Deploy
      displayName: Deploy to AKS
      environment: 'AKS_ENV.default'
      pool:
       vmImage: ubuntu-latest
      strategy:
       runOnce:
         deploy:
            steps:
            - task: DownloadPipelineArtifact@2
              inputs:
                buildType: 'current'
                artifactName: 'manifest'
                targetPath: '$(Pipeline.Workspace)/manifest'
            - task: KubernetesManifest@0
              inputs:
                action: 'createSecret'
                namespace: 'default'
                secretType: 'dockerRegistry'
                secretName: '$(acrsecretname)'
                dockerRegistryEndpoint: 'demoazureregistrytest'
            - task: HelmDeploy@0
              inputs:
                namespace: 'default'
                command: 'install'
                chartType: 'FilePath'
                chartPath: '$(Pipeline.Workspace)/manifest'
